import type { Metadata } from "next";

import { PrimeReactProvider } from 'primereact/api';
import Layout from "app/components/Layout/Layout";

import "primereact/resources/themes/saga-orange/theme.css";
import 'primeicons/primeicons.css';
import 'primeflex/primeflex.css';
import "app/styles/layout/layout.scss";
import "app/styles/home/index.scss";

import { StartApp } from "./api/database/facturacion/orm";
import "reflect-metadata";

export const metadata: Metadata = {
  title: "Panaderia",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  //StartApp()
  return (
    <PrimeReactProvider>
      <html lang="en">
        <body>
          <Layout>
            {children}
          </Layout>
        </body>
      </html>
    </PrimeReactProvider>
  );
}
